backend:
  name: git-gateway
  branch: main
media_folder: "images" # Carpeta para imágenes
public_folder: "/images" # URL pública de imágenes
collections:
  - name: "posts"
    label: "Posts"
    folder: "posts" # Carpeta de posts
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "featuredImage", widget: "image"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
